<a href="https://colab.research.google.com/github/vinaydsprj/Basic-ML/blob/main/classification_algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [13]:
dataset = pd.read_csv('Iris.csv')
# print(dataset)
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [14]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train ,y_test = train_test_split(X, y , test_size = 0.8 , random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

 Support vector machine Algo

In [16]:
from sklearn import svm
classifier = svm.SVC(kernel= 'rbf')
classifier.fit(X_train, y_train) 

SVC()

K nearest neighbour

In [17]:
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier()
# classifier.fit(X_train , y_train)

Naive Bayes

In [18]:
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# classifier.fit(X_train, y_train)

In [19]:
y_pred = classifier.predict(X_test)
#Checking the actual value and predicted value side by side
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
Accuracy = accuracy_score(y_test, y_pred)
print(Accuracy * 100)

[[40  0  0]
 [ 0 39  0]
 [ 0  3 38]]
97.5
